### ISSUE TITLE
thanks for starting this project

### ISSUE THREAD

**Issue by smashah** [FreePalestine1948/Boycott#1]
Hi there, thanks for taking the iniative to start this project. I would love to invite you to join other tech professionals in a centralized way via [techforpalestine](https://techforpalestine.org/)

A lot of us had different projects working on our own and now we are working together.

Thanks

**Comment by 0x0OZ** [comment]
Hi @smashah, 
First It is our responsibility to do all that we can for Palestine and its people towards their freedom. 

Also thank you for inviting us to this great project and community. We gladly accept the invite and look forward to being a part of it.
